### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [Stanford-Online/xblock-qualtrics-survey#13]
Hi there,

I wanted to know if `xblock-qualtrics-survey` xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @stvstnfrd

**Comment by stvstnfrd** [comment]
Following the sunset of the Lagunita project, this repo lives on under edx's stewardship at:
- https://github.com/edx/xblock-qualtrics-survey

This should have support through master/Juniper already.
